___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___
<center>*Copyright Pierian Data 2017*</center>
<center>*For more information, visit us at www.pieriandata.com*</center>

# NumPy Exercises
Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.

** IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output! **

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
zero_arr = np.zeros(10)

In [4]:
zero_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [90]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [2]:
#Jose Answer

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### Create an array of 10 ones

In [5]:
ones_arr = np.ones(10)

In [6]:
ones_arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
#Jose Answer

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

#### Create an array of 10 fives

In [14]:
my_list = [5,5,5,5,5]
fives_arr = np.array(my_list)

In [15]:
fives_arr

array([5, 5, 5, 5, 5])

In [16]:
#a different solution

In [17]:
new_fives_arr = ones_arr * 5

In [18]:
new_fives_arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [4]:
#Jose Answer

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

#### Create an array of the integers from 10 to 50

In [19]:
arr = np.arange(10,51)

In [20]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [5]:
#Jose Answer

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [21]:
even_arr = np.arange(10,51,2)

In [22]:
even_arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [6]:
#Jose Answer

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [25]:
mat = np.array([[0,1,2],[3,4,5],[6,7,8]])

In [26]:
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [91]:
np.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [92]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
#Jose Answer

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.ones((3,3)) #a tuple is entered into the function

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
#Jose Answer

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### Use NumPy to generate a random number between 0 and 1

In [39]:
np.random.rand() #see parenthesis are empty, so returns the number

0.6117329335290971

In [40]:
np.random.rand(1) #returns the number in an array

array([0.74601821])

In [93]:
np.random.rand(3)

array([0.66562754, 0.3643288 , 0.62301862])

In [94]:
np.random.rand(2,3)

array([[0.64272489, 0.41998182, 0.40324243],
       [0.39042033, 0.40618952, 0.07966611]])

In [15]:
#Jose Answer

array([ 0.42829726])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [43]:
np.random.randn(25) #all the numbers are in one row, one column

array([ 0.36434455,  0.35639352,  0.97971564,  0.44914172,  0.93997424,
        0.71991089,  0.52368797,  0.67525418, -0.34541222,  0.82274463,
       -0.27513638, -0.84372247,  0.37171336, -0.32512622,  0.94947357,
        1.08326209, -1.60664269,  0.25307418, -0.22757169,  0.49021478,
       -0.19833486, -0.65987424, -0.95958383,  1.68289633, -1.29273278])

In [89]:
np.random.randn(5,5) #the numers are in 5 rows, 5 columns

array([[-0.31232848,  0.33928471, -0.15590853, -0.50178967,  0.23556889],
       [-1.76360526, -1.09586204, -1.08776574, -0.30517005, -0.47374837],
       [-0.20059454,  0.35519677,  0.68951772,  0.41058968, -0.56497844],
       [ 0.59939069, -0.16293631,  1.6002145 ,  0.6816272 ,  0.0148801 ],
       [-0.08777963, -0.98211784,  0.12169048, -1.13743729,  0.34900258]])

In [33]:
#Jose Answer

array([ 1.32031013,  1.6798602 , -0.42985892, -1.53116655,  0.85753232,
        0.87339938,  0.35668636, -1.47491157,  0.15349697,  0.99530727,
       -0.94865451, -1.69174783,  1.57525349, -0.70615234,  0.10991879,
       -0.49478947,  1.08279872,  0.76488333, -2.3039931 ,  0.35401124,
       -0.45454399, -0.64754649, -0.29391671,  0.02339861,  0.38272124])

#### Create the following matrix:

In [56]:
np.linspace(0.01,1,100).reshape(10,10)


array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [35]:
#Jose Answer

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [96]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [57]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [36]:
#Jose Answer

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [58]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [59]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [40]:
#Jose Answer

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [60]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [62]:
mat[3,4]

20

In [41]:
#Jose Answer

20

In [63]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [72]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [42]:
#Jose Answer

array([[ 2],
       [ 7],
       [12]])

In [73]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [75]:
mat[-1][::]

array([21, 22, 23, 24, 25])

In [46]:
#Jose Answer

array([21, 22, 23, 24, 25])

In [76]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [77]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [49]:
#Jose Answer

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [78]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [79]:
np.sum(mat) #using the sum function

325

In [97]:
mat.sum()  #using the sum method on the array object

325

In [50]:
#Jose Answer

325

#### Get the standard deviation of the values in mat

In [80]:
np.std(mat)

7.211102550927978

In [51]:
#Jose Answer

7.2111025509279782

#### Get the sum of all the columns in mat

In [81]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [82]:
mat[0] + mat[1] + mat[2] + mat[3] + mat[4] #mat[0] is row at index 0 which is an array itself and so on

array([55, 60, 65, 70, 75])

In [98]:
mat.sum(axis = 0) #Sums along down the rows on the 0 axis, so it sums the column

array([55, 60, 65, 70, 75])

In [100]:
mat.sum(axis = 1) #Sums along the columns on the 1 axis, so it sumes the rows

array([ 15,  40,  65,  90, 115])

In [53]:
#Jose Answer

array([55, 60, 65, 70, 75])

## Bonus Question

We worked a lot with random data with numpy, but is there a way we can insure that we always get the same random numbers? [Click Here for a Hint](https://www.google.com/search?q=numpy+random+seed&rlz=1C1CHBF_enUS747US747&oq=numpy+random+seed&aqs=chrome..69i57j69i60j0l4.2087j0j7&sourceid=chrome&ie=UTF-8)

# Great Job!