In [1]:
import numpy as np

In [2]:
#vectors are one dimension arrays, i.e. a straight list
#matrices are two dimensional but can sometimes have only one row or one column 

In [4]:
#creating numpy array

my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [5]:
x = np.array(my_list)

In [6]:
x

array([1, 2, 3])

In [7]:
type(x)

numpy.ndarray

In [8]:
#use a nested list to create a matrix
my_matrix = [[1,2,3], [4,5,6], [6,7,8]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [10]:
#built in methods to generate arrays

In [11]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [13]:
np.arange(0,5)  #numpys version of range is arange, array range

array([0, 1, 2, 3, 4])

In [14]:
np.arange(0,11,2) #even numbers

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
type(0.) #most numbers in numpy and pandas are floating point numbers

float

In [20]:
np.zeros((3,5)) #pass in a tuple to get a matrix of zeros. Rows x columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [25]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
#linspace stands for linearly spaced

In [28]:
np.linspace(0,10,3) #gives you 3 evenly spaced number between 0 and 10, notice 10 is inclusive

array([ 0.,  5., 10.])

In [30]:
np.linspace(0,10,30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [31]:
np.linspace(0,10,51)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [32]:
#identity matrix

In [34]:
np.eye(4) #only needs one argument as identity matrix always has the same number of rows and columns

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
#numpys random library

In [36]:
#in a uniform distribution all the numbers between 0 and 1 have the same probability of being picked

In [38]:
np.random.rand(1) #a random number between 0 and 1

array([0.744185])

In [42]:
np.random.rand(5,5)  #5 by 5 matrix of random numbers between 0 and 1 taken from a uniform distribution, i.e all have the 
                     #same chance of being picked

array([[0.53059905, 0.96185315, 0.76222161, 0.32571036, 0.50560495],
       [0.76369665, 0.11303896, 0.33495601, 0.21690348, 0.56297318],
       [0.43198376, 0.46126966, 0.51122113, 0.28183351, 0.76479585],
       [0.16924071, 0.11298376, 0.82324172, 0.1559169 , 0.41863448],
       [0.6546552 , 0.29888873, 0.65371292, 0.07648251, 0.43541749]])

In [44]:
#standard normal distribution, bell curve. The closer you are to 0 the higher probability of being picked
#also called a gaussian distrubution.

In [46]:
np.random.randn(5) #5 numbers randomly drawn from a normal distribution.

array([ 0.12120162, -0.5140365 , -1.94990893, -2.8754558 , -1.24240084])

In [47]:
np.random.randn(5,4)

array([[-1.81160313,  2.4186082 , -0.2514445 ,  0.96104818],
       [ 1.19446025, -1.10835422,  1.33624112,  0.94863266],
       [-1.10335384,  0.83600822,  1.65599221, -0.33546998],
       [-0.76924873,  1.95396543,  0.80102842,  0.14371116],
       [-0.46850263,  0.76156875,  1.39440592,  1.37427894]])

In [49]:
np.random.randint(1,100) #random integer between low and high, exclusive of high

20

In [50]:
np.random.randint(1,100,10) # 10 random integers between low and high(exclusive)

array([88, 91,  6,  6, 75, 31, 21, 49, 60, 66])

In [51]:
#array attributes and methods

In [65]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [66]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [67]:
ranarr

array([33, 24,  5,  4, 24, 25,  6,  0, 14, 38])

In [68]:
#reshape method returns an array with the same data but a new shape

In [69]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [70]:
#shape attribute tells us the shape of the array

In [71]:
arr.shape  #attribute not a method so no need for ()

(25,)

In [72]:
arr.reshape(5,5).shape

(5, 5)

In [73]:
ranarr

array([33, 24,  5,  4, 24, 25,  6,  0, 14, 38])

In [74]:
ranarr.max()

38

In [75]:
ranarr.argmax() #returns the index position of the max number

9

In [76]:
ranarr.min()

0

In [77]:
ranarr.argmin()

7