In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[3]  #returns the element at index position 3. Same as list indexing

3

In [6]:
arr[1:4] #same as list slicing. Grab starting at index position 1, and go up to but not including index position 4

array([1, 2, 3])

In [7]:
arr[:4]

array([0, 1, 2, 3])

In [8]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
#numpy arrays differ from a python list because of their ability to broadcast

In [10]:
#broadcasting allows me to take a slice of the array and reassign the values 

In [11]:
arr[0:5] = 60   #this change takes effect in place

In [12]:
arr

array([60, 60, 60, 60, 60,  5,  6,  7,  8,  9, 10])

In [13]:
#the permanent change takes affect even if you use a new variable. See below

In [14]:
arr = np.arange(0,11)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
slice_of_array = arr[0:5]

In [17]:
slice_of_array[::] = 60

In [18]:
slice_of_array

array([60, 60, 60, 60, 60])

In [19]:
arr

array([60, 60, 60, 60, 60,  5,  6,  7,  8,  9, 10])

In [20]:
#so the above data in the original array was not copied to slice_of_array, it is just a view of the original array
#this is due to memory problems that can happen when working with arrays
#to overcome this you need explicityly state that you want to copy and create a new variable, shown below

In [21]:
arr = np.arange(0,11)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr_new = arr.copy()

In [24]:
arr_new

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr_new[0:3] = 20

In [26]:
arr_new

array([20, 20, 20,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
#notice the original arr is not change this time

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
#now lets look at indexing a matrix(a 2 dimensional array)

In [30]:
#mat [row,col]
#mat[row][col]

In [31]:
mat = np.array([[5,10,15],[20,25,30],[35,40,45]]) #notice this is one list containing 3 list. Using 3 list alone will
                                                  #not work

In [32]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [33]:
mat[0] #index the entire first row

array([ 5, 10, 15])

In [34]:
mat[1,1] #to grab an individual element

25

In [35]:
mat[1][1]

25

In [36]:
mat[0,2]

15

In [37]:
#2D array slicing

In [38]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [39]:
mat[0:2,1:] #grab rows at index position 0 up to but not including row at index position 2.
            #within those rows grab columns starting at column index 1 up to the end

array([[10, 15],
       [25, 30]])

In [40]:
mat[1:,0:2]

array([[20, 25],
       [35, 40]])

In [41]:
#conditional selection

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [44]:
bool_arr = arr > 4

In [45]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [46]:
arr[bool_arr] #this returns the values where the index location matches True in the bool_arr

array([ 5,  6,  7,  8,  9, 10])

In [47]:
arr #original arr not change

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
#to do more efficiently

In [49]:
arr[arr > 4] #notice square brackets as conditional selection is a bit like you are indexing the True elements

array([ 5,  6,  7,  8,  9, 10])

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
new_arr = arr[arr>4]

In [52]:
new_arr

array([ 5,  6,  7,  8,  9, 10])

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [58]:
arr[arr>4 and arr<9]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()