In [1]:
import numpy as np

In [2]:
arr = np.arange(0,10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr + arr #you can add arrays together. Addition is done based of index position. 
          #elements at index 0 get added together, elements at index 1 get added, etc

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr/arr  #this is a warning as opposed to an error. It is produced because of the zero division.
         #notice nan(N/A) is placed at the index where division by 0 took place but the other elements were divided
         #as expected

C:\Users\pnair\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [13]:
1/arr #if 1 is divided by zero inf(infinity) gets places at the index position where the division took place

C:\Users\pnair\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [14]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr **3 #everything in the array to the power of 3. Using a scaler

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [17]:
arr + 12 #12 gets added to everything in the array. Using a scaler

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [18]:
#numpy comes with many built in functions that can be applied to every element in the array

In [25]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [20]:
np.exp(arr)  #e to the power of everything in the array

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [21]:
np.max(arr) #a numpy function that passes in the array object

9

In [22]:
arr.max() #a method called off the array object. 

9

In [23]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [24]:
np.log(arr)

C:\Users\pnair\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])